name: Deploy

on:
  check_run:
    types: [completed]

jobs:
  Connect to server:
    runs-on: ubuntu-20.04
    uses: webfactory/ssh-agent@v0.4.0
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          ssh-public-key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}
      - name: Connect through SSH
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
      - name: Test
        run: cat /home/winc/test.txt
        run: exit