name: Run Tests

on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.0'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  start-deploy-if-success:
    name: Start Deployment to Server
    runs-on: ubuntu-20.04
    needs: [run-tests]
    steps:
      - name: ssh to server
      - run: ssh winc@167.71.9.171